In [ ]:
### import numpy as np

# -------- Matrix Input Function --------
def input_matrix(name):
    rows = int(input(f"\nEnter number of rows for Matrix {name}: "))
    cols = int(input(f"Enter number of columns for Matrix {name}: "))
    
    matrix = []
    print(f"\nEnter elements of Matrix {name} row-wise:")

    for i in range(rows):
        row = list(map(float, input(f"Row {i+1}: ").split()))
        
        if len(row) != cols:
            print("❌ Invalid input! Please enter correct number of elements.")
            return input_matrix(name)
        
        matrix.append(row)
    
    return np.array(matrix)

# -------- Display Function --------
def display(title, matrix):
    print("\n" + "="*40)
    print(f"{title}")
    print("="*40)
    print(matrix)
    print("="*40)

# -------- Main Program --------
while True:
    print("\n\n===== MATRIX OPERATIONS TOOL =====")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Transpose")
    print("5. Determinant")
    print("6. Exit")

    choice = input("Enter your choice (1-6): ")

    # -------- Addition --------
    if choice == "1":
        A = input_matrix("A")
        B = input_matrix("B")

        if A.shape == B.shape:
            display("Addition Result (A + B)", A + B)
        else:
            print("❌ Matrices must be of same size!")

    # -------- Subtraction --------
    elif choice == "2":
        A = input_matrix("A")
        B = input_matrix("B")

        if A.shape == B.shape:
            display("Subtraction Result (A - B)", A - B)
        else:
            print("❌ Matrices must be of same size!")

    # -------- Multiplication --------
    elif choice == "3":
        A = input_matrix("A")
        B = input_matrix("B")

        if A.shape[1] == B.shape[0]:
            result = np.dot(A, B)
            display("Multiplication Result (A × B)", result)
        else:
            print("❌ Columns of A must equal rows of B!")

    # -------- Transpose --------
    elif choice == "4":
        A = input_matrix("A")
        display("Transpose of Matrix A", A.T)

    # -------- Determinant --------
    elif choice == "5":
        A = input_matrix("A")

        if A.shape[0] == A.shape[1]:
            det = np.linalg.det(A)
            print("\nDeterminant:", round(det, 2))
        else:
            print("❌ Determinant only for square matrix!")

    # -------- Exit --------
    elif choice == "6":
        print("\n✅ Thank you for using Matrix Operations Tool!")
        break

    else:
        print("❌ Invalid choice! Try again.")



===== MATRIX OPERATIONS TOOL =====
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Enter your choice (1-6):  1

Enter number of rows for Matrix A:  12 
Enter number of columns for Matrix A:  34



Enter elements of Matrix A row-wise:


Row 1:  12


❌ Invalid input! Please enter correct number of elements.



Enter number of rows for Matrix A:  45
Enter number of columns for Matrix A:  67



Enter elements of Matrix A row-wise:


Row 1:  99


❌ Invalid input! Please enter correct number of elements.



Enter number of rows for Matrix A:  1
Enter number of columns for Matrix A:  3



Enter elements of Matrix A row-wise:


Row 1:  2


❌ Invalid input! Please enter correct number of elements.



Enter number of rows for Matrix A:  3
Enter number of columns for Matrix A:  3



Enter elements of Matrix A row-wise:


Row 1:  1 2 3
Row 2:  4 5 6
Row 3:  6 7 9

Enter number of rows for Matrix B:  3
Enter number of columns for Matrix B:  3



Enter elements of Matrix B row-wise:


Row 1:  2 4 6 
Row 2:  3 5 7 
Row 3:  9 8 7



Addition Result (A + B)
[[ 3.  6.  9.]
 [ 7. 10. 13.]
 [15. 15. 16.]]


===== MATRIX OPERATIONS TOOL =====
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit
